# For more info see: https://github.com/apify/pull-request-toolkit-action/
name: Apify PR toolkit

on:
  pull_request:
    branches:
      - master
    types: ['opened', 'reopened', 'synchronize', 'labeled', 'unlabeled', 'edited', 'ready_for_review'] # The first 3 are default.

concurrency: # This is to make sure that it's executed only for the most recent changes of PR.
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  apify-pr-toolkit:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    steps:
      - name: clone pull-request-toolkit-action
        uses: actions/checkout@v3
        with:
          repository: apify/pull-request-toolkit-action
          path: ./.github/actions/pull-request-toolkit-action

      - name: run pull-request-toolkit action
        uses: ./.github/actions/pull-request-toolkit-action
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_GITHUB_TOKEN }}
          zenhub-token: ${{ secrets.PULL_REQUEST_TOOLKIT_ACTION_ZENHUB_TOKEN }}
